family=socket.AF_INET if there is no ipv6 support
This should help with errors like:
  TypeError: getaddrinfo() argument 1 must be string or None

In cases where Python does not support IPv6 but the underlying
network stack of the operating system does.